version: '3.8'

services:
  malware-db:
    image: postgres
    container_name: malware-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "malware_api_development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - malware-api-network

  malware-pgadmin:
    image: dpage/pgadmin4
    container_name: malware-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@malware.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "15432:80"
    depends_on:
      - malware-db
    networks:
      - malware-api-network

  malware-api:
    image: malware-api
    container_name: malware-api
    build: .
    environment:
      - DBHOST=malware-db
      - DBUSER=postgres
      - DBPASS=password
    volumes:
      - .:/malware-app
    ports:
      - "3000:3000"
    depends_on:
      - malware-db
    networks:
      - malware-api-network

networks:
  malware-api-network:
    driver: bridge

volumes:
  postgres: