version: '3.8'

services:
  # PostgreSQL Database Service
  malware-db:
    image: postgres
    container_name: malware-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "malware_api_development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - malware-api-network

  # pgAdmin Service for Database Management
  malware-pgadmin:
    image: dpage/pgadmin4
    container_name: malware-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@malware.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "15432:80"
    depends_on:
      - malware-db
    networks:
      - malware-api-network

  # Ruby on Rails API Service
  malware-api:
    # The image name for the built container
    image: malware-api
    container_name: malware-api
    # Build context for Docker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DBHOST: malware-db
      DBUSER: postgres
      DBPASS: password
    volumes:
      # Mount the current directory (malware_app) to /malware-app in the container
      - .:/malware_app
    ports:
      - "3000:3000"
    depends_on:
      - malware-db
    networks:
      - malware-api-network

# Network Configuration
networks:
  malware-api-network:
    driver: bridge

# Volume Configuration
volumes:
  postgres:
