default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DBHOST'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>

development:
  <<: *default
  database: malware_api_development

test:
  <<: *default
  database: malware_api_test

production:
  <<: *default
  database: malware_api_production
  username: malware_api
  password: <%= ENV["MALWARE_API_DATABASE_PASSWORD"] %>